# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
# version must contains build number to make sure that all commits are processed by appveyor.
# If build number is not part of the version than appveyor build fails with the following message: "Build version x.y.z already exists."

#version: 1.2.3.{build}
#version: "{build}"
version: "{branch} (#{build})"

# branches to build
branches:
  only:
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true
  - git config --get core.autocrlf
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)

# clone directory
clone_folder: c:\projects\veyortests

# environment variables
environment:
  MY_VARIABLE: foobar

# scripts that run after cloning repository
install:
- cmd: echo INSTALL SCRIPT RUNNING!
- cmd: call .\ci\appveyor\ant_install.bat
- ps: .\ci\appveyor\debug.ps1
- ps: .\ci\appveyor\read_version.ps1
- ps: .\ci\appveyor\prepare_github_deploy.ps1
- cmd: call .\ci\appveyor\list_env_var.bat
#- ps: .\ci\appveyor\install_github_package.ps1 -name "win32Arduino" -installpath "c:\projects\veyortests\third_party" -url "http://codeload.github.com/end2endzone/win32Arduino/zip/v2.0.0.37"
#- ps: .\ci\appveyor\install_github_package.ps1 -name "googletest"   -installpath "c:\projects\veyortests\third_party" -url "http://codeload.github.com/google/googletest/zip/release-1.6.0"
#Testing absolute path with PowerShell scripts:
- ps: .\ci\appveyor\hello.ps1 -Name Tony
- ps: . "$env:APPVEYOR_BUILD_FOLDER\ci\appveyor\hello.ps1" -Name Thor
#FAILS: - ps: $env:APPVEYOR_BUILD_FOLDER\ci\appveyor\hello.ps1 -Name Peter
- ps: $(APPVEYOR_BUILD_FOLDER)\ci\appveyor\hello.ps1 -Name Steve

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform: x86

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  project: foobar\foobar.sln
  verbosity: minimal
  
#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
- cmd: echo RUNNING TESTS!
- cmd: echo APPVEYOR_BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
- cmd: ren foobar\Release\foobar.exe foobar_v%PRODUCT_VERSION%.exe 
- cmd: dir /b foobar\Release\foobar*.exe

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: foobar\Release\*.exe
  name: foobar binary
  
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
- provider: GitHub
  tag: $(GITHUB_TAG_NAME)
  release: $(GITHUB_RELEASE_NAME)
  description: Latest successful AppVeyor CI builds of branch '$(APPVEYOR_REPO_BRANCH)', commit $(APPVEYOR_REPO_COMMIT)
  auth_token:
    secure: BgyLisMc154qWpkyBdh8OD+D9HMM+YnBkh7H4MEUShKO3aCU+Fn/XVGJ07fTsRmH
  artifact: /(.*\.zip|.*\.exe)/
  draft: false           #true means release is private (visible to contributors only), false is public (visible to everyone)
  prerelease: true       #true for prerelease, false to identify this release as the 'latest release'
  force_update: true
