# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.2.3.{build}

# branches to build
branches:
  only:
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# clone directory
clone_folder: c:\projects\veyortests

# environment variables
environment:
  MY_VARIABLE: foobar

# scripts that run after cloning repository
install:
- cmd: echo INSTALL SCRIPT RUNNING!
- cmd: set
#- cmd: call ci\appveyor\override_build_version.bat
- ps: .\ci\appveyor\override_build_version.ps1 -Target AppVeyor

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform: x86

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  project: foobar\foobar.sln
  verbosity: minimal
  
#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
- cmd: echo RUNNING TESTS!
- cmd: echo APPVEYOR_BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
- cmd: ren foobar\Release\foobar.exe foobar_v%APPVEYOR_BUILD_VERSION%.exe 

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: foobar\Release\*.exe
  name: foobar binary
  
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:

  # Deploy to GitHub Releases
- provider: GitHub
  tag: $(GITHUB_TAG_NAME)
  release: $(GITHUB_RELEASE_NAME)
  description: Latest successful AppVeyor CI builds of branch '$(APPVEYOR_REPO_BRANCH)', commit $(APPVEYOR_REPO_COMMIT)
  auth_token:
    secure: BgyLisMc154qWpkyBdh8OD+D9HMM+YnBkh7H4MEUShKO3aCU+Fn/XVGJ07fTsRmH
  artifact: /(.*\.zip|.*\.exe)/
  draft: false
  prerelease: true
  force_update: true

  
#investigate having 2 github provider for Nightly build of branch 'foo'
#see details at https://github.com/ASOS/OctopusStepTemplateCi/blob/master/appveyor.yml
