echo Override APPVEYOR_BUILD_VERSION script...
echo APPVEYOR_BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
echo overriding...
set APPVEYOR_BUILD_VERSION=3.4.5.%APPVEYOR_BUILD_NUMBER%
echo APPVEYOR_BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
echo done
echo.
